### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by Cherubin7th** [holtzy/R-graph-gallery#1]
Hi couldn't find any information(neither on the website nor here) about the license.
It is problematic to use any code or picture without a license.
Could you add a license?

**Comment by holtzy** [comment]
Thanks for your interest.

There is no licence curently. I should do it for sure.

Use code and graphics if you want, but please cite the gallery and the related contributor when there is one.

All the best,

Yan

Le 20/10/2016 à 16:45, Cherubin7th a écrit :

Hi couldn't find any information(neither on the website nor here) about the license.
It is problematic to use any code or picture without a license.
Could you add a license?

**Comment by paulkaefer** [comment]
This is no longer an issue, per [LICENSE](https://github.com/holtzy/R-graph-gallery/blob/master/LICENSE).

**Comment by holtzy** [comment]
Indeed! Thanks
