### ISSUE TITLE
data_frame used without loading dplyr

### ISSUE THREAD

**Issue by moi-taiga** [holtzy/R-graph-gallery#107]
In **Interactive network chart with R** , `data_frame` is used without loading **dplyr**. I don't know whether the correct way would be to library(dplyr), or to use data.frame, or even tibble()?

**Comment by JosephBARBIERDARNAL** [comment]
Hi @moi-taiga !
`data_frame()` is just used because it's convenient data format for network analysis, hope this answer your question (:
