### ISSUE TITLE
Circular packing with hidden first level of hierarchy

### ISSUE THREAD

**Issue by WD-Microer** [holtzy/R-graph-gallery#12]
> ggraph(mygraph, layout = 'circlepack', weight="size") + 
+   geom_node_circle(aes(fill = as.factor(depth), color = as.factor(depth) )) +
+   scale_fill_manual(values=c("0" = "white", "1" = viridis(4)[1], "2" = viridis(4)[2], "3" = viridis(4)[3], "4"=viridis(4)[4])) +
+   scale_color_manual( values=c("0" = "white", "1" = "black", "2" = "black", "3" = "black", "4"="black") ) +
+   geom_node_label( aes(label=new_label), size=4) +
+   theme_void() + 
+   theme(legend.position="FALSE", plot.margin = unit(rep(0,4), "cm"))

**Error in tree_to_hierarchy(graph, direction, sort.by, weight) : 
  Weight must be numeric**

why?

**Comment by TarsLi** [comment]
Hi,
I got the same problem and my solution was to remove the quotes for size:
ggraph(mygraph, layout = 'circlepack', **weight=size**).
Hope it helps you.

**Comment by ravichandrasekaran** [comment]
Also referenced in the `ggraph` package repo issues here: https://github.com/thomasp85/ggraph/issues/231
