### ISSUE TITLE
Change in paletteer

### ISSUE THREAD

**Issue by EmilHvitfeldt** [holtzy/R-graph-gallery#13]
slight warning. New version of `paletteer` (1.0.0) have change in syntax. 
So it would be

```r
paletteer_c("nord::frost")
``` 

instead of

```r
paletteer_c(package = "nord", palette = "frost")
```

**Comment by holtzy** [comment]
Thanks @EmilHvitfeldt.

Years later, I've finally updated the website thanks to @JosephBARBIERDARNAL's help! 😅

Thanks for `paletteer`, it's awesome!
