### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by biwabel** [holtzy/R-graph-gallery#131]
The link to the csv file is not valid anymore:

https://github.com/holtzy/R-graph-gallery/blame/0f54d335588a4d074f47bcac9abae58aa5bf5f58/318-custom-dygraphs-time-series-example.Rmd#L47

Keep up the good work!

**Comment by JosephBARBIERDARNAL** [comment]
I can't find the original dataset, any idea @holtzy ?

**Comment by holtzy** [comment]
The dataset is lost forever, it was hosted on the very old Wordpress version of my Python site 😢

@JosephBARBIERDARNAL can you try to rebuild it? Check this link it has it I reckon:
https://medium.com/@manoramu/bike-sharing-dataset-data-set-linear-regression-project-1cc150db9358

**Comment by JosephBARBIERDARNAL** [comment]
fixed with #162
