### ISSUE TITLE
Tukey test result display on boxplots

### ISSUE THREAD

**Issue by rionlerm** [holtzy/R-graph-gallery#15]
Hi,

I am running your code for producing boxplots from Tukey results however, I run into various errors starting stemming from this dataset:

`head(dat2)`
row.names              DATE TEMP   RH LOC
1 2019-08-06 17:13:48 28.6 40.0  AC
2 2019-08-06 17:33:48 27.6 41.9  AC
3 2019-08-06 17:53:48 27.3 43.4  AC
4 2019-08-06 18:13:48 27.1 44.7  AC
5 2019-08-06 18:33:48 27.1 45.9  AC
6 2019-08-06 18:53:48 26.9 47.2  AC

The code hereafter where errors stem from is parsed as follows:

`generate_label_df <- function(testMulti, variable){
  testMulti.levels <- testMulti[[variable]][,4]
  testMulti.labels <- data.frame(multcompLetters(testMulti.levels)['Letters'])
  testMulti.labels$treatment = rownames(testMulti.labels)
  testMulti.labels = testMulti.labels[order(testMulti.labels$LOC) , ]
  return(testMulti.labels)
}
labels <- generate_label_df(testMulti, "subset$LOC")`

It currently produces this:

`Error in order(testMulti.labels$LOC) : argument 1 is not a vector `

Let me know if you need additional info because basically I need to display TEMP (values) and how it differed significantly among LOC (locations).

**Comment by holtzy** [comment]
Hi,
Thx for the feedback but I do not provide 1:1 help in github issues. All the best, Yan
