### ISSUE TITLE
Compact letter display on small multiple boxplot

### ISSUE THREAD

**Issue by najouamghazli** [holtzy/R-graph-gallery#16]
Hello,
I have multiple small ggplot (boxplots) with different values (pH and nitrogen) and some metals in mg/g. I would like to add cld to these boxplots, do you have an idea on how to do this ?
Here's what I'v done so far:

```
PCparam <- read.table("PCResultsWithReplicats.tsv", dec = ",", header = TRUE)
PCparam.melt <- melt(PCparam)
p <- ggplot(data = PCparam.melt, aes(x=variable, y=value)) + 
  geom_boxplot(aes(fill=Cells)) +
  scale_fill_manual(values = Couleurs.cells)
p + facet_wrap( ~ variable, scales="free")
```
And for ANOVA and TukeyHSD test I did this:

```
anovares <- aov(value ~ variable, data = PCparam.melt)
summary(anovares )
anovares2 <- aov(value ~ Cells * variable, data = PCparam.melt)
summary(anovares2 )
THSD <- TukeyHSD(anovares2 )
```
Thank you

**Comment by holtzy** [comment]
Hi,
Sorry but I do not provide 1:1 help in github issues. Wish you the best for your work and sorry for the inconvenience. Yan
