### ISSUE TITLE
Problems in solving analyzes in the ecological database

### ISSUE THREAD

**Issue by kadin14** [holtzy/R-graph-gallery#165]
[dados_analise.txt](https://github.com/holtzy/R-graph-gallery/files/14807204/dados_analise.txt)
[matriz_atributos.csv](https://github.com/holtzy/R-graph-gallery/files/14807211/matriz_atributos.csv)
[matriz_comunidade.csv](https://github.com/holtzy/R-graph-gallery/files/14807212/matriz_comunidade.csv)
[script_composição e diversidade (1).txt](https://github.com/holtzy/R-graph-gallery/files/14807214/script_composicao.e.diversidade.1.txt)

#muito usados em análises ecológicas:
install.packages("FD")
library(FD)
install.packages("ade4")
library(ade4)
install.packages("picante")
library(picante)
install.packages("vegan")
library(vegan)

#muito usados em análises gráficas:
install.packages("ggplot2")
library(ggplot2)
install.packages("gridExtra")
library(gridExtra)
install.packages("ggrepel")
library(ggrepel)
install.packages("GGally")
library(GGally)

#abrir a planilha dos dados 1° abra a (matriz da comunidade) e 2° abra (matriz de atributos)
comm <- read.csv(file.choose(), header = T, row.names = 1, sep = ";")
att <- read.csv(file.choose(), header = T, row.names = 1, sep = ";")

is.data.frame(comm)
is.data.frame(att)

summary (comm)
summary (att)

comm
att

#os nomes das esp?cies devem ser iguais e estar na mesma ordem nas duas planilhas.Substituindo os nomes das esp?cies de um por outro

colnames(comm) <- rownames (att)
# determina??o de uma matriz de dist?ncia entre as esp?cies em fun??o dos atributos avaliados.  Neste caso, foi usado a dist?ncia de Gower, tendo em 
# em vista a exist?ncia de vari?veis categ?ricas.

att.dis <- gowdis(att) #onde att.dis, representa o objeto criado a partir da importacao do arquivo att.csv importado

#transforma??o de uma matriz de dist?ncia n?o-euclidiana em euclidiana por meio de do m?todo de Calliez

att.cal <- cailliez(att.dis, TRUE)

## PCoA dos atributos categóricos

# 1. Selecionar somente os atributos categóricos

# 2. Calcular a distância de Gower
dist_categ <- gowdis(att)

# 3. PCoA da matriz de distância funcional (Gower)
pcoa_traits_cat <- pcoa(dist_categ, correction = "cailliez")

# 4. Exportar dados (escores) para ggplot
eixos_cat <- as.data.frame(pcoa_traits_cat$vectors[,1:2]) # Selecionar os dois primeiros eixos

# 5. Gráfico de ordenação
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2)) + 
  geom_point(pch = 21, size = 4, alpha = 0.7, color = "black", fill = "cyan4") + 
  geom_text_repel(aes(Axis.1, Axis.2, label = rownames(eixos_cat))) +
  geom_hline(yintercept = 0, linetype = 2) + 
  geom_vline(xintercept = 0, linetype = 2) +
  labs(x = "PCO 1", y = "PCO 2", title = "Dados categóricos") 
plot_trait_cat

# Pacotes necessários
install.packages("FD")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("ade4")

library(FD)
library(ggplot2)
library(ggrepel)
library(ade4)

# Calcular a distância de Gower
dist_categ <- gowdis(att)

# PCoA da matriz de distância funcional (Gower)
pcoa_traits_cat <- pcoa(dist_categ, correction = "cailliez")

# Exportar dados (escores) para ggplot
eixos_cat <- as.data.frame(pcoa_traits_cat$vectors[,1:2]) 

# Gráfico de ordenação com ajuste de rótulos e adição de legenda
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2)) + 
  geom_point(aes(color = rownames(eixos_cat)), size = 4, alpha = 0.7) + 
  geom_text_repel(aes(label = rownames(eixos_cat)), size = 3, box.padding = 0.5, 
                  point.padding = 0.5, segment.color = "transparent") +
  geom_hline(yintercept = 0, linetype = 2, color = "grey") + 
  geom_vline(xintercept = 0, linetype = 2, color = "grey") +
  labs(x = "PCO 1", y = "PCO 2", title = "Ordenação dos Atributos Categóricos", 
       color = "Espécies") +
  theme_minimal() +
  theme(legend.position = "bottom")

plot_trait_cat

# Gráfico de ordenação com grade e outras personalizações
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2, label = rownames(eixos_cat))) + 
  geom_point(pch = 19, size = 4, alpha = 0.7, color = "darkblue", fill = "cyan3") + 
  geom_text_repel(size = 3, segment.color = 'transparent') +
  labs(x = "PCO 1", y = "PCO 2", title = "Ordenação de Atributos Categóricos") +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none") +
  geom_hline(yintercept = 0, linetype = 2, color = "gray") +
  geom_vline(xintercept = 0, linetype = 2, color = "gray")

plot_trait_cat

# Definindo a cor dos pontos com base nos quadrantes
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2, label = rownames(eixos_cat))) + 
  geom_point(aes(color = ifelse(Axis.1 >= 0 & Axis.2 >= 0, "Quadrante 1",
                                ifelse(Axis.1 < 0 & Axis.2 >= 0, "Quadrante 2",
                                       ifelse(Axis.1 < 0 & Axis.2 < 0, "Quadrante 3", "Quadrante 4")))), 
             pch = 19, size = 4, alpha = 0.7) + 
  geom_text_repel(size = 3, segment.color = 'transparent') +
  labs(x = "PCO 1", y = "PCO 2", title = "Ordenação de Atributos Categóricos") +
  scale_color_manual(values = c("Quadrante 1" = "darkblue", "Quadrante 2" = "darkgreen", 
                                "Quadrante 3" = "darkred", "Quadrante 4" = "orange")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none") +
  geom_hline(yintercept = 0, linetype = 2, color = "gray") +
  geom_vline(xintercept = 0, linetype = 2, color = "gray")

plot_trait_cat

###ESSE É O CERTO

# Definindo a cor dos pontos com base nos quadrantes
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2, label = rownames(eixos_cat))) + 
  geom_point(aes(color = ifelse(Axis.1 >= 0 & Axis.2 >= 0, "Quadrante 1",
                                ifelse(Axis.1 < 0 & Axis.2 >= 0, "Quadrante 2",
                                       ifelse(Axis.1 < 0 & Axis.2 < 0, "Quadrante 3", "Quadrante 4")))), 
             pch = 19, size = 4, alpha = 0.7) + 
  geom_text_repel(aes(label = gsub("_", " ", rownames(eixos_cat))), size = 3, segment.color = 'transparent', family = "italic") +  # Deixar os nomes em itálico e sem underscore
  labs(x = "PCO 1", y = "PCO 2", title = "Atributos categóricos") +
  scale_color_manual(values = c("Quadrante 1" = "darkblue", "Quadrante 2" = "darkgreen",                       "Quadrante 3" = "darkred", "Quadrante 4" = "orange")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white")) +
  geom_hline(yintercept = 0, linetype = 2, color = "gray") +
  geom_vline(xintercept = 0, linetype = 2, color = "gray")

plot_trait_cat

# Salvar a figura em alta resolução (600 DPI)
ggsave("plot_trait_cat.png", plot_trait_cat, dpi = 600)

## Calcular a correlação entre os eixos da PCoA e os atributos originais
# 1. Execute a análise de ajuste dos atributos categóricos novamente (substitua 'dist_categ' e 'att' pelos seus próprios dados)
env_fit <- envfit(dist_categ ~ ., data = att, perm = 999)

# 2. Verifique se não há erros na análise
print(env_fit)

# Extrair as coordenadas dos eixos da PCoA
pcoa_coords <- scores(pcoa_object)

# Calcular as correlações entre as coordenadas dos eixos da PCoA e os atributos originais
correlations <- cor(pcoa_coords, att)

# Visualizar as correlações em forma de tabela
print(correlations)

#

############################################333
# Carregar pacotes necessários
library(vegan)
library(ggplot2)
library(ggrepel)

# 1. Calcular a distância Gower para dados categóricos
dist_categ <- vegdist(dados_categoricos, method = "gower")

# 2. Realizar a PCoA
pcoa_traits_cat <- cmdscale(dist_categ, k = 2, eig = TRUE)

# Converter o resultado da PCoA em um data frame
eixos_cat <- as.data.frame(pcoa_traits_cat$points)

# Adicionar nomes das linhas (se necessário)
rownames(eixos_cat) <- rownames(pcoa_traits_cat$points)

# Adicionar grupos (se necessário)
eixos_cat$grupo <- att$grupo

# 3. Criar o gráfico de dispersão
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2, label = rownames(eixos_cat))) + 
  geom_point(aes(color = ifelse(Axis.1 >= 0 & Axis.2 >= 0, "Quadrante 1",
                                ifelse(Axis.1 < 0 & Axis.2 >= 0, "Quadrante 2",
                                       ifelse(Axis.1 < 0 & Axis.2 < 0, "Quadrante 3", "Quadrante 4")))), 
             pch = 19, size = 4, alpha = 0.7) + 
  geom_text_repel(aes(label = gsub("_", " ", rownames(eixos_cat))), size = 3, segment.color = 'transparent', family = "italic") +  # Deixar os nomes em itálico e sem underscore
  labs(x = "PCO 1", y = "PCO 2", title = "Atributos categóricos") +
  scale_color_manual(values = c("Quadrante 1" = "darkblue", "Quadrante 2" = "darkgreen",                     "Quadrante 3" = "darkred", "Quadrante 4" = "orange")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white")) +
  geom_hline(yintercept = 0, linetype = 2, color = "gray") +
  geom_vline(xintercept = 0, linetype = 2, color = "gray")

# 4. Visualizar o gráfico de dispersão
plot_trait_cat

# 5. Salvar a figura em alta resolução (600 DPI)
ggsave("plot_trait_cat.png", plot_trait_cat, dpi = 600)

# 6. Realizar a análise de ajuste ambiental novamente
env_fit <- envfit(dist_categ ~ ., data = att, perm = 999)

# 7. Verificar os resultados da análise de ajuste ambiental
print(env_fit)

# Definindo a cor dos pontos com base nos quadrantes
# Definindo a cor dos pontos com base nos quadrantes
plot_trait_cat <- ggplot(eixos_cat, aes(x = Axis.1, y = Axis.2, label = rownames(eixos_cat))) + 
  geom_point(aes(color = ifelse(Axis.1 >= 0 & Axis.2 >= 0, "Quadrante 1",
                                ifelse(Axis.1 < 0 & Axis.2 >= 0, "Quadrante 2",
                                       ifelse(Axis.1 < 0 & Axis.2 < 0, "Quadrante 3", "Quadrante 4")))), 
             pch = 19, size = 4, alpha = 0.7) + 
  geom_text_repel(aes(label = gsub("_", " ", rownames(eixos_cat))), size = 3.4, segment.color = 'transparent', family = "italic", max.overlaps = Inf) +  # Deixar os nomes em itálico e sem underscore
  labs(x = "PCO 1", y = "PCO 2", title = "Atributos categóricos") +
  scale_color_manual(values = c("Quadrante 1" = "darkblue", "Quadrante 2" = "darkgreen", 
                                "Quadrante 3" = "darkred", "Quadrante 4" = "orange")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white")) +
  geom_hline(yintercept = 0, linetype = 2, color = "gray") +
  geom_vline(xintercept = 0, linetype = 2, color = "gray")

plot_trait_cat

#
# Salvar a figura em alta resolução (600 DPI) com dimensões 10x10 polegadas como arquivo PNG
ggsave("Figure2.png", plot = last_plot(), width = 9, height = 9, dpi = 400)

############################################

### Riqueza de espécies
richness <- dbFD(att.dis, comm)$nbsp 
head(richness)

#COMPOSIÇÃO FUNCIONAL (CWM)
functcomp(x = att, a = as.matrix(comm), CWM.type = c("dom"))

# Functional Richness
fric <- dbFD(att.dis, comm)$FRic

head(fric)

## Functional Diversity 
# Passo 1: análise de agrupamento para criar o dendrograma. 
dend <- hclust(att.dis, "average")
plot(dend)

# Passo 2: transformar o dengrograma em um arquivo da classe phylo.
tree_dend <- as.phylo(dend)

# Passo 3: calcular o valor da diversidade funcional. 
FD <- pd(comm, tree_dend)$PD
head(FD)

#> 
#> ## "Functional Divergence" s
fdiv <- dbFD(att.dis, comm)$FDiv

head(fdiv)

# "Functional Dispersion" 
fdis <- dbFD(att.dis, comm)$FDis

head(fdis)

#> ## "Functional evenness" 
feve <- dbFD(att.dis, comm)$FEve

head(feve)
#>
#>
#>## Gráficos
## Você pode criar uma tabela com os resultados de todas as métricas
metricas <- data.frame(richness = richness,
                       FD_gp = FD,
                       fric = fric,
                       fdiv = fdiv,
                       fdis = fdis,
                       feve = feve)
head(metricas)
write.table(metricas, "metricas.csv", row.names=T, sep=",", dec=".")
## Gráfico para comparar o comportamento das métricas
ggpairs(metricas) 

#MODELOSNULOS (regra de montagem de comunidades)

P<-((length(which(((feve) <0.4)==TRUE)))+((length(which(((feve)==0.4)==TRUE)))/2))/1001
P
SES<-2*(P-0.5)
SES

################
Make a phylogenetic tree with R code from a spreadsheet using a megatree published with V.PhyloMaker.

#V.PhyloMaker: doi.org/10.1111/ecog.04434
#phytools: doi.org/10.1111/j.2041-210X.2011.00169.x

#Install packages

#devtools::install_github("jinyizju/V.PhyloMaker")
#install.packages("ape")
#install.packages("phangorn")
#install.packages("phytools")
#install.packages("geiger")
install.packages("htmltools")
install.packages("picante")
install.packages("V.PhyloMaker2")
library(V.PhyloMaker2)
library(picante)
library(htmltools)

#defina o diretorio
setwd("~/ANALISE DE FILOGENIA/DADOS COM ESPECIES EXCLUIDAS")
#carregando planilha
dados <- read.table("dados_analise.txt", h=T, stringsAsFactors = T)

#separar especies, genero e familia 
summary(dados)

dados_filogenia<- as.data.frame(dados[,c(3,4,5)])
# criar a matriz de distância filogenética
library(ape)
dist_phylo <- cophenetic(phylo.maker(dados_filogenia)$phylo)

#Note: 1 taxa fail to be binded to the tree, especie ""Piranhea_securinega" não foi encotrada/ excluida
library(dplyr)
dados_atual<-filter(dados,species != "Piranhea_securinega")
summary(dados_atual)
dim(dados)
dim(dados_atual)# as linhas com a especie Piranhea_securinega foram excluidas 

#rodando a analise filogenetica sem a especie excluida.

dados_filogenia_atual<- as.data.frame(dados_atual[,c(3,4,5)])
# criar a matriz de distância filogenética
library(ape)
dist_phylo <- cophenetic(phylo.maker(dados_filogenia_atual)$phylo)

#todas as especies foram encontradas na arvore 42 especies ....

summary(dados_filogenia_atual)
#Load packages
library(V.PhyloMaker)
library(phytools)

#Create phylogenetic tree (esse comando demora um pouco a rodar)
phy <- phylo.maker(dados_filogenia_atual)

phy$species.list

###usando apenas o cenario 3
#You only need part of this object to draw your tree.
#Extract the useful part 
tree <- phy$scenario.3
plot(tree)
#Plot the tree
phytools::plotTree(tree)
read.tree

# Plotar a árvore com as distâncias nas arestas
plot.phylo(tree, show.node.label = TRUE, edge.width = 1)

#outro jeito de plotar a arvore... 
phytools::plotTree(tree,type="fan",fsize=0.7,lwd=1,
         ftype="i")

# Carregar o pacote necessário
library(ape)

# Plotar a árvore com cores nos nós
plot(tree, type = "fan", cex = 0.8, lwd = 5)

# Definir as cores para os nós da árvore
cores <- c("red", "blue", "green", "purple")  # Defina as cores desejadas

# Adicionar cores aos rótulos dos nós
nodelabels(pch = 21, bg = cores)
tiff("arvore.tiff", width = 800, height = 600)  # Ajuste os valores de largura e altura conforme necessário
plot(tree, type = "fan", cex = 0.5, lwd = 5)
nodelabels(pch = 21, bg = cores)
dev.off()

#fazendo de outra forma

# Carregar o pacote necessário
library(ape)

# Plotar a árvore com cores nos nós
plot(tree, type = "fan", cex = 0.8, lwd = 5)

# Definir as cores para os nós da árvore
cores <- c("red", "blue", "green", "purple")  # Defina as cores desejadas

# Adicionar cores aos rótulos dos nós
nodelabels(pch = 21, bg = cores)

# Obter as distâncias das arestas
edge.dist <- tree$edge.length

# Adicionar as distâncias como rótulos nos nós
nodelabels(text = round(edge.dist, 2), frame = "none", cex = 0.6, adj = c(0.5, -0.2), col = "black", font = 1)

tiff("arvore.tiff", width = 800, height = 600)  # Ajuste os valores de largura e altura conforme necessário
plot(tree, type = "fan", cex = 0.5, lwd = 5)
nodelabels(pch = 21, bg = cores)
dev.off()

####deu bom srsrs

#some information
tree$Nnode
tree$edge.length
tree$edge
tree$node.label
tree$tip.label
sum(tree$edge.length)

##salvando a tree
write.tree(tree, "Ecofilotree2.csv")

#Export the tree for manual editing or use in other software
write.tree(tree, "tree.tre")
#Note the .tre file extension here

#Import the tree back into R
#Or import a tree made with other software into R
tree = read.tree("tree.tre")

#fazer arvore usando o ggplot

## instal ggtree para fazer a arvore
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

#BiocManager::install("ggtree")
library(ggtree)
ggtree(tree)
ggtree(tree)+geom_tiplab()

#viewClade(p,MRCA(p, tip=("I", "L")))

##################### novo codigo 
#M?tricas com dendogramas====
#_Diversidade filogen?tica====
library(ape)
library(picante)

#tree <- read.tree("ants.phylo.txt") #Olhem a estrutura do arquivo .txt. Essa ? uma forma que comumente encontramos arquivos de dendogramas filogen?ticos. Para organizar isso utilizamos a fun??o read.tree() do pacote ape
plot(tree, cex=0.6) #Visualizando o dendograma

#montando a tabela de comunidade
dados_atual #dados  
library(reshape2)
summary(dados_atual)
com<- dcast(dados_atual,area~species,value.var = "species") #data frame da comunidade
colnames(com)
com<-com[,-c(1)]

#Para calcular a diversidade filogen?tica de cada uma das esp?cies do dados atual precisamos de uma medida de dist?ncia filogen?tica entre pares de esp?cies. Como a ?rvore filogen?tica permite calcular isso, podemos utilizar a dist?ncia cofen?tica para obter a dist?ncia entre esp?cies par-a-par.
phydist <- cophenetic(tree)
phydist
dim(phydist)

#Agora, confira se todas as esp?cies das comunidades est?o na matriz de dist?ncias filogen?ticas.
summary(colnames(com) %in% colnames(phydist))

##PD##
#Agora calculamos a diversidade filogen?tica com o ?ndice PD de Faith (1992).
#O objeto aqui ? a ?rvore filogen?tica: tree
PD <- pd(com, tree)

#criando uma tabela com os resultados de PD, MPD, MNTD
(tabela_resultados <- as.data.frame(PD))

# Calcular a MNTD (distância média entre as espécies) usando a matriz de distância filogenética
(MNTD <- mean(phydist))
#adicionando a distancia média (MNTD) nos resultados
(tabela_resultados$MNTD<-MNTD)
tabela_resultados

##MPD##
#Agora vamos calcular a diversidade filogen?tica com o ?ndice MPD de Webb et al. (2002).
#O objeto aqui ? a dist?ncia par-a-par gerada da ?rvore filogen?tica: phydist
(tabela_resultados$MPD <- mpd(com, phydist))
tabela_resultados

names(tabela_resultados)
tabela_resultados$MNTD
tabela_resultados$PD
tabela_resultados$MPD

#exportando tabela de resultados 

#Diversidade taxonomica====
#_Metricas Classicas====
library(vegan)
library(dplyr)
library(hillR)
library(GGally)
library(vegan)
library(iNEXT)
library(ggplot2)
library(tidyverse)
library(reshape2)

head(dados) #Primeiras linhas da tabela
summary(dados) #Sum?rio da tabela
str(dados) #Estrutura da tabela
names(dados) #Nomes das colunas da tabela

#PARA CORIBE 

dados_formatados_coribe <- dcast(dados, area~species, value.var = "species")
summary(dados_formatados_coribe)

com_coribe <- dados_formatados_coribe[,-c(1)]

#_Numeros de Hill
# q=0 == species richness
(tabela_resultados$Species_Richness_q0 <- hill_taxa(comm = com_coribe, q = 0, MARGIN = 1)) #Hill q=0 
tabela_resultados
# q=1 == Shannon diversity/entropy
(tabela_resultados$Shannon_q1 <- hill_taxa(comm = com_coribe, q = 1, MARGIN = 1)) #Hill q=1
# q=2 == Simpson diversity
(tabela_resultados$Simpson_q2 <- hill_taxa(comm = com_coribe, q = 2, MARGIN = 1)) #Hill q=2
tabela_resultados

#medtricas classicas 
#_Shannon-Wiener (H')
#Quanto maior o valor de H', maior ? a diversidade.
tabela_resultados$H_shannon <- diversity(x = com_coribe, index = "shannon")

#_Simpson
(tabela_resultados$D_simpson <- diversity(x = com_coribe, index = "simpson"))

#_Riqueza
(tabela_resultados$sp_rich <- specnumber(com_coribe))

#_Abund?ncia
(tabela_resultados$sp_abund <- rowSums(com_coribe))
tabela_resultados

#salvando a tabela com as metricas da comunidade 
write.csv2(tabela_resultados,"metricas_comunidade")

# Cobertura amostral ====

out1 <- iNEXT(t(com_coribe), q=0, datatype="abundance") 
out1$DataInfo

(plot_sp <- ggiNEXT(out1, type=1, se=TRUE, grey=FALSE) 
  + theme_classic(base_size = 18) 
  + theme(legend.position="right")
  + labs(y="Número de espécies", x = "Núnero de individuos"))

#plot para cobertura amostral
(plot_C_amnostral <- ggiNEXT(out1, type=2, se=TRUE, grey=FALSE) 
  + theme_classic(base_size = 18) 
  + theme(legend.position="right")
  + labs(y="Cobertura amostral", x = "Número de individuos"))

###aqui usa os dados da parcel, area em função da especie 

# DIVERSIDADE ====
#ajeitando os dados para o formato correto (comprido) separando por data e local
dados_formatados <- dcast(dados, area+parcela~species, value.var = "species")
summary(dados_formatados)

com <- dados_formatados[,-c(1,2)] #Novo objeto agora s? com a comunidade, apenas as esp?cies!!

#_Numeros de Hill
# q=0 == species richness
(Species_Richness_q0 <- hill_taxa(comm = com, q = 0, MARGIN = 1)) #Hill q=0 
# q=1 == Shannon diversity/entropy
(Shannon_q1 <- hill_taxa(comm = com, q = 1, MARGIN = 1)) #Hill q=1
# q=2 == Simpson diversity
(Simpson_q2 <- hill_taxa(comm = com, q = 2, MARGIN = 1)) #Hill q=2

#criar uma tabela com todas as metricas para incluir as metricas 
(tab_result <- data.frame(dados_formatados[,c(1,2)], Species_Richness_q0,Shannon_q1,Simpson_q2)) #Olha como ficou legal! =D

# Especifique o caminho do arquivo CSV que você deseja salvar
caminho_arquivo <- "~/ANALISE DE FILOGENIA/DADOS COM ESPECIES EXCLUIDAS/tabela_resultados.csv"

# Salvar a tabela em formato CSV
write.csv(tab_result, file = caminho_arquivo, row.names = FALSE)

#_Abund?ncia
(tab_result$sp_abund <- rowSums(com))

##_Plotagem====
library(reshape2)
str(tab_result)
tab_ggplot <- melt(tab_result, id= c("area","parcela")) 

#Criar uma tabela longa, o ggplot usa matriz de dados e norteia pelosnomes das colunas
head(tab_ggplot) #Primeiras linhas da tabela
dim(tab_ggplot) #Dimens?o [linhas , colunas]

cor_plot <- c("green", "gray80") #Objeto com as cores que ser?o utilizadas

library(ggplot2)
ggplot(tab_ggplot, aes(x=area  , y=value, fill=area  )) +
  geom_boxplot()+ #fazer um boxplot
  theme_bw()+ #um tema, sair do fundo cinza #Inserir as cores
  facet_wrap(~variable, scales = "free")+
scale_fill_manual(values ="#1B9E77")+
  stat_summary(fun.data ="mean_se",geom = "point",size=2.5)

**Comment by holtzy** [comment]
?
