### ISSUE TITLE
Waffle good charts

### ISSUE THREAD

**Issue by holtzy** [holtzy/R-graph-gallery#168]
https://twitter.com/_ansgar/status/1510002806580727810
https://isabella-b.com/blog/my-life-in-months/
https://github.com/BjnNowak/book/blob/main/script/waffle_chart_distribution.Rmd
https://github.com/BjnNowak/TidyTuesday/blob/main/animal_feeds.R
https://twitter.com/imagineazhar/status/1642754792509550594

**Comment by JosephBARBIERDARNAL** [comment]
- 1: to discuss
- 2: to discuss
- 3: done ✅
- 4: missing data ❌
- 5: done ✅

**Comment by holtzy** [comment]
2: forget about it

**Comment by holtzy** [comment]
4: asked for data

**Comment by JosephBARBIERDARNAL** [comment]
fixed with #180 can close
