### ISSUE TITLE
"forcats" is still spelled wrong in HTML file

### ISSUE THREAD

**Issue by angela-li** [holtzy/R-graph-gallery#17]
It looks like this has been fixed in the Rmd by @Rekyt in commit 1a65db2, but the Rmd has not been re-knit to propagate the changes to the HTML ([link to HTML doc here](https://github.com/holtzy/R-graph-gallery/blob/188750e6fbb619162f6e1fe5c49199d5df9baccf/267-reorder-a-variable-in-ggplot2.html#L170))

Do you have continuous integration (Travis, Github Actions) on this repository, or are Rmds re-knit by hand locally?

**Comment by holtzy** [comment]
It's knitted manually :(
Just fixed it.
Thanks
