### ISSUE TITLE
Check the Map section following the recently merge PR #95

### ISSUE THREAD

**Issue by holtzy** [holtzy/R-graph-gallery#176]

**Comment by kadyb** [comment]
It looks like this page has not been updated: https://r-graph-gallery.com/325-background-map-from-geojson-format-in-r.html

Rmd: https://github.com/holtzy/R-graph-gallery/blob/master/325-background-map-from-geojson-format-in-r.Rmd

**Comment by kadyb** [comment]
It would be nice to update this image too: https://r-graph-gallery.com/img/other/backgroundMapExplanation.png
I mean to replace `rgdal` and `geojsonio` with `sf`.

**Comment by JosephBARBIERDARNAL** [comment]
everything should be fixed will the #183 PR

**Comment by kadyb** [comment]
Looks great!
