### ISSUE TITLE
External data source may be permanently down

### ISSUE THREAD

**Issue by ndporter** [holtzy/R-graph-gallery#199]
The shapefile source for [Choropleth mapping with leaflet](https://github.com/holtzy/R-graph-gallery/blob/master/183-choropleth-map-with-leaflet.Rmd) and some of the other mapping examples, `http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip` is returning a 404 error (as of 2024-May-31). The domain abruptly ceased appearing in the [Wayback machine](https://web.archive.org/web/20240415000000*/thematicmapping.org) in December 2023 and hasn't had a single capture in 2024 either, suggesting it may be long term. The original Zip file can be [downloaded from the Wayback machine](https://web.archive.org/web/20240415000000*/http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip) at the November 2023 image, but if the site remains down, a more reliable link should be found or created and the page updated.

**Comment by JosephBARBIERDARNAL** [comment]
hi @ndporter ! thank you for your invaluable help! the .zip will now be directly in the repo to avoid this type of error. we'll have it fixed by the next pull request!
