### ISSUE TITLE
How the animation plots are embedded in the website

### ISSUE THREAD

**Issue by huyingjie** [holtzy/R-graph-gallery#2]
@holtzy Your website is amazing. Recently I am trying to embedded animation plots on my blog. In the future, I will create project websites from scratch and this requires embedding plots in HTML files. I do not want to use `Rmd`, shiny, or `blogdown`. 

I searched online tutorials of ggiraph and plotly. All of them do not mention how to do it. How did you achieve that? How do you know which JavaScript library one R animation package is using?

**Comment by holtzy** [comment]
Hi @huyingjie,

Thanks for your message. The method I use is:

1/ make your interactive plot with any html widget. Like:
`library(plotly)`
`p=ggplot(.......)`
`widg=ggplotly(p)`

2/ Save it as an .html file using the htmlwidget library
`library(htmlwidgets)`
`saveWidget(widg, file = "path/file.html", selfcontained = TRUE)`

3/ Host this html with the other media of your website

4/ Embed it in a page of your website. This is done using an iframe in your html code:
`<iframe width="1300" height="300" src="https://mywebsite/media/path/file.html" frameborder="40"></iframe>`

You can see an example with an interactive leaflet map [here](https://www.r-graph-gallery.com/map/). Hope it helps!

Yan

**Comment by huyingjie** [comment]
I tried it on hexo blog. It will automatically convert saved html files into a post, then embedded this post in the iframe.
![screen shot 2017-12-17 at 11 29 09 pm](https://user-images.githubusercontent.com/4664280/34090020-248d0a22-e382-11e7-95e9-992920dbd4ca.png)
