### ISSUE TITLE
Circular bar plots examples don't show intended gaps

### ISSUE THREAD

**Issue by diazdc** [holtzy/R-graph-gallery#21]
Hello, 

Thanks for amazing R figure examples. I noticed that the examples with circular bar plots don't produce the intended gaps between groups. It seems that this is caused by the groups in the sample data not being factorized.

Cheers, 

Daniel

**Comment by mfoulds** [comment]
This fixed the problem for me:
data <- 
    data %>%
        mutate(group = as.factor(group))

**Comment by JosephBARBIERDARNAL** [comment]
Hi @diazdc ! Thanks for your comment and sorry for the late reply 

Do you know where this problem occurs? I can't find it in the gallery
