### ISSUE TITLE
R - multcompLetters Error undefined columns selected

### ISSUE THREAD

**Issue by laonese** [holtzy/R-graph-gallery#216]
Hello everyone, 
I have a problem with the multcompLetters4 function. I have done anova and tukey test and now I want to generate letters for a boxplot with the function. I have seen a youtube video and did it exactly as in the video, but I get an error that I don't understand.

This is my code:

SAD_data_Spur_mai_2019 <- SAD_data %>%
  filter(Saison == 2019, Monat == 5, Art == "S. purpurea")

anova <- aov(`Geh DT SAD (mg/g)` ~ Individuum, data = SAD_data_Spur_mai_2019)
summary(anova)

tukey <- TukeyHSD(anova)
print(tukey)

cld <- multcompLetters4(anova, tukey)
print(cld)

When i run it I get the following error:

Error in `[.data.frame`(data, , fm[[1]]) : 
  undefined columns selected
  
The result of the anova and tukey test is as follows:
> summary(anova)
            Df Sum Sq Mean Sq F value   Pr(>F)    
Individuum   7  32006    4572   20.88 6.33e-07 ***
Residuals   16   3503     219                     
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> 
> tukey <- TukeyHSD(anova)
> print(tukey)
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = `Geh DT SAD (mg/g)` ~ Individuum, data = SAD_data_Spur_mai_2019)

$Individuum
                                 diff         lwr         upr
14_Spur_f_BT-01_Spur_m_BT  -26.739473  -68.567057  15.0881111
15_Spur_f_BT-01_Spur_m_BT   26.327669  -15.499915  68.1552532
46_Spur_f_BT-01_Spur_m_BT  -41.324086  -83.151670   0.5034978
47_Spur_f_BT-01_Spur_m_BT   23.937801  -17.889782  65.7653854
48_Spur_m_BT-01_Spur_m_BT   56.764234   14.936650  98.5918175
49_Spur_m_BT-01_Spur_m_BT  -52.430203  -94.257787 -10.6026190
50_Spur_f_BT-01_Spur_m_BT  -36.311685  -78.139269   5.5158991
15_Spur_f_BT-14_Spur_f_BT   53.067142   11.239558  94.8947260
46_Spur_f_BT-14_Spur_f_BT  -14.584613  -56.412197  27.2429707
47_Spur_f_BT-14_Spur_f_BT   50.677274    8.849690  92.5048582
48_Spur_m_BT-14_Spur_f_BT   83.503706   41.676122 125.3312904
49_Spur_m_BT-14_Spur_f_BT  -25.690730  -67.518314  16.1368538
50_Spur_f_BT-14_Spur_f_BT   -9.572212  -51.399796  32.2553719
46_Spur_f_BT-15_Spur_f_BT  -67.651755 -109.479339 -25.8241714
47_Spur_f_BT-15_Spur_f_BT   -2.389868  -44.217452  39.4377162
48_Spur_m_BT-15_Spur_f_BT   30.436564  -11.391020  72.2641483
49_Spur_m_BT-15_Spur_f_BT  -78.757872 -120.585456 -36.9302882
50_Spur_f_BT-15_Spur_f_BT  -62.639354 -104.466938 -20.8117702
47_Spur_f_BT-46_Spur_f_BT   65.261888   23.434304 107.0894715
48_Spur_m_BT-46_Spur_f_BT   98.088320   56.260736 139.9159036
49_Spur_m_BT-46_Spur_f_BT  -11.106117  -52.933701  30.7214671
50_Spur_f_BT-46_Spur_f_BT    5.012401  -36.815183  46.8399852
48_Spur_m_BT-47_Spur_f_BT   32.826432   -9.001152  74.6540161
49_Spur_m_BT-47_Spur_f_BT  -76.368004 -118.195588 -34.5404205
50_Spur_f_BT-47_Spur_f_BT  -60.249486 -102.077070 -18.4219024
49_Spur_m_BT-48_Spur_m_BT -109.194437 -151.022020 -67.3668526
50_Spur_f_BT-48_Spur_m_BT  -93.075918 -134.903502 -51.2483345
50_Spur_f_BT-49_Spur_m_BT   16.118518  -25.709066  57.9461020
                              p adj
14_Spur_f_BT-01_Spur_m_BT 0.3933857
15_Spur_f_BT-01_Spur_m_BT 0.4111698
46_Spur_f_BT-01_Spur_m_BT 0.0540480
47_Spur_f_BT-01_Spur_m_BT 0.5215084
48_Spur_m_BT-01_Spur_m_BT 0.0045869
49_Spur_m_BT-01_Spur_m_BT 0.0092309
50_Spur_f_BT-01_Spur_m_BT 0.1145835
15_Spur_f_BT-14_Spur_f_BT 0.0083286
46_Spur_f_BT-14_Spur_f_BT 0.9182967
47_Spur_f_BT-14_Spur_f_BT 0.0122493
48_Spur_m_BT-14_Spur_f_BT 0.0000758
49_Spur_m_BT-14_Spur_f_BT 0.4394725
50_Spur_f_BT-14_Spur_f_BT 0.9911607
46_Spur_f_BT-15_Spur_f_BT 0.0008144
47_Spur_f_BT-15_Spur_f_BT 0.9999990
48_Spur_m_BT-15_Spur_f_BT 0.2547920
49_Spur_m_BT-15_Spur_f_BT 0.0001511
50_Spur_f_BT-15_Spur_f_BT 0.0017916
47_Spur_f_BT-46_Spur_f_BT 0.0011838
48_Spur_m_BT-46_Spur_f_BT 0.0000102
49_Spur_m_BT-46_Spur_f_BT 0.9795015
50_Spur_f_BT-46_Spur_f_BT 0.9998513
48_Spur_m_BT-47_Spur_f_BT 0.1866024
49_Spur_m_BT-47_Spur_f_BT 0.0002154
50_Spur_f_BT-47_Spur_f_BT 0.0026218
49_Spur_m_BT-48_Spur_m_BT 0.0000025
50_Spur_f_BT-48_Spur_m_BT 0.0000200
50_Spur_f_BT-49_Spur_m_BT 0.8727430

in my opinion there is no problem, but the error still occurs. i hope someone of you can help me. 
Thanks!

**Comment by JosephBARBIERDARNAL** [comment]
hello @laonese 
issues of the [r-graph-gallery.com](https://r-graph-gallery.com/) are just for problems related to the website and the associated code.
