### ISSUE TITLE
Outdated link to "cheatsheet section"

### ISSUE THREAD

**Issue by yvonnefroehlich** [holtzy/R-graph-gallery#238]
It looks like the "cheatsheet section" was moved to another place, as the link https://r-graph-gallery.com/cheatsheet.html does not resolve anymore.

https://github.com/holtzy/R-graph-gallery/blob/34cf5baff5d98d2a6d9ece551a651b4e9087b3d1/6-graph-parameters-reminder.Rmd#L45

So far I could not figure out the new place to update the link.

**Comment by JosephBARBIERDARNAL** [comment]
Hi @yvonnefroehlich ! I can't find it either, @holtzy any idea? Otherwise I will just remove this Note

**Comment by yvonnefroehlich** [comment]
> Hi @yvonnefroehlich ! I can't find it either, @holtzy any idea? Otherwise I will just remove this Note

Thanks for looking at this issue. I just opended PR #248 to remove this note. I

**Comment by holtzy** [comment]
Removed. Thanks all!
