### ISSUE TITLE
Customized choropleth map code missing

### ISSUE THREAD

**Issue by zilch42** [holtzy/R-graph-gallery#27]
Hi there. Firstly thanks for this amazing resource.

[https://www.r-graph-gallery.com/327-chloropleth-map-from-geojson-with-ggplot2.html](https://www.r-graph-gallery.com/327-chloropleth-map-from-geojson-with-ggplot2.html)
On this page there is a section that says: "There is a bit of work to do to get a descent figure. We need to change the color palette, improve the legend, use a log scale transformation for the colorscale, change background and add titles and explanation. Here is the code to do that, and the final result!"

But there is no code or link to another page with the code.

**Comment by Vane-AR** [comment]
I was just about to report the same issue! Did you get any update?

**Comment by holtzy** [comment]
Thanks for the report. This should be fixed now. Can you confirm it suits your needs?

**Comment by zilch42** [comment]
Yep! Can see it now. Thank you
