### ISSUE TITLE
'tm_map' applied to an object of class "list"

### ISSUE THREAD

**Issue by MaPengyu** [holtzy/R-graph-gallery#3]
#http://www.r-graph-gallery.com/102-text-mining-and-wordcloud/
#102 TEXT MINING AND WORDCLOUD

I followed this code and got an error :
`
> dataset_corpus_all <- tm_map(dataset_corpus_all, removePunctuation)
Error in UseMethod("tm_map", x) : 
  no applicable method for 'tm_map' applied to an object of class "list"
`

**Comment by holtzy** [comment]
Hi,
Sorry for this code issue. I'm currently working on a new version of the R
graph gallery and will take it into account.
Best,
Yan

**Comment by vasili111** [comment]
>I'm currently working on a new version of the R graph gallery
Hi,
When you plan to release new version?

**Comment by Aman-Gupta-9293** [comment]
yes ,you are use for a new version software
