### ISSUE TITLE
Incorrect node orientation in circular dendrogram 

### ISSUE THREAD

**Issue by sufkes** [holtzy/R-graph-gallery#43]
When I run the circular dendrogram example at https://www.r-graph-gallery.com/339-circular-dendrogram-with-ggraph.html , it works, except that the node at 12 o'clock is 66, rather than 1. I can't find any way to adjust the orientation of the nodes. ggraph seems to ignore the 'offset' option in this case.

**Comment by sufkes** [comment]
![image](https://user-images.githubusercontent.com/28952185/113574435-1b6dd200-95ea-11eb-87cd-76595d54304e.png)

**Comment by BjnNowak** [comment]
Hi,
Also tried this method to label circular dendrogram but, unlike polar barplot, I think it can't work coz it seems that we can't control node position. So we don't know which node will be on top.
Anyway, thanks for all the info on the website!

**Comment by holtzy** [comment]
👋 Hi and thanks for the feedback!
I'm a bit confused here, should I change something on. the gallery? Or a new example fixing your problem 🤔

**Comment by holtzy** [comment]
All good then, closing the issue!
