### ISSUE TITLE
Boxplot with jitter bug

### ISSUE THREAD

**Issue by holtzy** [holtzy/R-graph-gallery#47]
Your graphing tutorials are great! I have been using this example and really like it: https://www.r-graph-gallery.com/96-boxplot-with-jitter.html

I just updated R and Rstudio and now its not working and after a day of trying to get it to work and trying to sort out which packages I lost, I figured I would try out your email before giving up.

This line 
levelProportions <- summary(data$names)/nrow(data)

Now generates the error "Error in summary(data$names)/nrow(data) : 
  non-numeric argument to binary operator”

But even removing the “amount” option in the jitter() function or giving it just some constant I am not able to get this to work

Any hints would be very appreciated!

Sincerely,

Ashley

**Comment by JosephBARBIERDARNAL** [comment]
I believe the error comes from the following code snippet:

```
names <- as.factor(c(rep("A", 80) , rep("B", 50) , rep("C", 70)))
value <- c( rnorm(80 , mean=10 , sd=9) , rnorm(50 , mean=2 , sd=15) , rnorm(70 , mean=30 , sd=10) )
data <- data.frame(names,value)
 
# Basic boxplot
boxplot(data$value ~ data$names , col=terrain.colors(4) )
 
# Add data points
mylevels <- levels(data$names)
levelProportions <- summary(data$names)/nrow(data)
for(i in 1:length(mylevels)){
 
  thislevel <- mylevels[i]
  thisvalues <- data[data$names==thislevel, "value"]
   
  # take the x-axis indices and add a jitter, proportional to the N in each level
  myjitter <- jitter(rep(i, length(thisvalues)), amount=levelProportions[i]/2)
  points(myjitter, thisvalues, pch=20, col=rgb(0,0,0,.9)) 
   
}
```

This **does not** lead to any error for me, but I'm note sure why this used to. I guess we can close this issue?
