### ISSUE TITLE
failed to customize the fill when plotting circular packing

### ISSUE THREAD

**Issue by Zhang-Jianwei-issas** [holtzy/R-graph-gallery#57]
Hi Yan,

Thank you for your great page, I like it a lot.
Right now I am working on a circular packing plot.

I think I correctly prepared the data set for plotting circular packing using function `ggplot`. 
I got an error when I set the fill for multiple groups in a specific hierarchy level.

**Worked**. When I use function `scale_color_brewer(palette = "Paired)`, it filled accordingly, but lack of available colors (**n = 12**) for my groups (**n = 15**).

**Failed**. I created multiple discrete values using the function, and then use the function `scale_color_manual(values = c())`, but it filled. Two or three groups were filled with unknown colors, the remaining groups were filled with blank, and the highest hierarchy were filled with **grey**. 

I struggled for two days, but without any progress.

Any help would be very appreciated.

**Comment by holtzy** [comment]
Hi,
Sorry I do not provide individual help since I receive too much and don't have the bandwidth.
