### ISSUE TITLE
Fix opengraph metadata

### ISSUE THREAD

**Issue by luxedo** [holtzy/R-graph-gallery#64]
Currently the previews of the pages is not working:
![Screenshot from 2021-09-04 10-35-19](https://user-images.githubusercontent.com/14118472/132096283-9880d2bf-93d8-4c33-aaa7-264e40d4630d.png)

https://www.opengraph.xyz/url/https%3A%2F%2Fwww.r-graph-gallery.com%2F/

even though there is opengraph metadata in `index.html`

https://github.com/holtzy/R-graph-gallery/blob/e912fe836cd0e2cfbaab01f3ef3f899e0ea929ed/index.html#L43-L46

It seems that the image is is missing the root slash and `www`:
Today:
[https://r-graph-gallery.comimg/overview_RGG.png](https://r-graph-gallery.comimg/overview_RGG.png)
Correct
[https://www.r-graph-gallery.com/img/overview_RGG.png](https://www.r-graph-gallery.com/img/overview_RGG.png)

**Comment by luxedo** [comment]
I 've sent a PR trying to fix it but I don't think I can test it

https://github.com/holtzy/R-graph-gallery/pull/65

**Comment by holtzy** [comment]
Thanks, I fixed it on my side!
