### ISSUE TITLE
Dataset can't be found

### ISSUE THREAD

**Issue by zhiiiyang** [holtzy/R-graph-gallery#7]
https://github.com/holtzy/R-graph-gallery/blob/84d017da74c6c6e85f55d76030fb44160494114b/332-hexbin-chloropleth-cartogram.Rmd#L112

Hey Holtz, thank you for building the wonderful website. 
One of the input files for the cartogram plot example seems to be missing. Can you point me to the right place to retrieve this dataset? Thank you!

**Comment by holtzy** [comment]
This has been fixed if I'm not mistaken
