### ISSUE TITLE
Post #182 disappeared

### ISSUE THREAD

**Issue by holtzy** [holtzy/R-graph-gallery#72]
[Blogpost](https://www.r-graph-gallery.com/182-add-circles-rectangles-on-leaflet-map.html) this post disappeared :(

**Comment by JosephBARBIERDARNAL** [comment]
running `git log --full-history -- "182-add-circles-rectangles-on-leaflet-map.Rmd"` did not find anything

**Comment by JosephBARBIERDARNAL** [comment]
does that look like it? 

https://web.archive.org/web/20171128051153/http://www.r-graph-gallery.com:80/182-add-circles-rectangles-on-leaflet-map

**Comment by holtzy** [comment]
Please re-create the post!

**Comment by holtzy** [comment]
🎉
