### ISSUE TITLE
Bug in Circular Stacked Barplot code

### ISSUE THREAD

**Issue by trekonom** [holtzy/R-graph-gallery#75]
Hi Yan,
thanks for your great work and the R graph gallery. Always my place to start when trying to implement a new chart type.

I stumbled over a small bug in the [Circular Stacked Barplot](https://github.com/holtzy/R-graph-gallery/blob/218144656d0347e3ec1ee8e7aec41a888781c062/299-circular-stacked-barplot.Rmd) code when answering [this](https://stackoverflow.com/questions/71487387/circular-stacked-barplot-in-r/71487582#71487582) question on SO.

My guess is that the reason for this bug is that as of version 4.0.0 R treats strings in data frames as strings rather than factors.

**Comment by JosephBARBIERDARNAL** [comment]
Hi @trekonom ! thanks a lot for your feedback!

This will be fixed with #182 
We can close this issue now
