### ISSUE TITLE
R graph gallery website broken 

### ISSUE THREAD

**Issue by waynelapierre** [holtzy/R-graph-gallery#87]
https://www.r-graph-gallery.com/

Opening this link shows nothing but a word "forbidden".

**Comment by holtzy** [comment]
Everything works well for me 

Can you tell me a bit more?
- location
- browser
- screenshot

Anything that can help me understand the issue?

**Comment by waynelapierre** [comment]
location: USA
browser: chrome 
screenshot: I am not sure how to attach a picture, but the whole page is blank except the word "forbidden" show on the top left.

**Comment by waynelapierre** [comment]
I still have this issue. I kind of remember that this issue happened one or two months ago. Could you please check if this website got any web traffic from USA Chrome users in the past month? So I can see if this issue is specific to me.
