### ISSUE TITLE
Update maps section

### ISSUE THREAD

**Issue by dieghernan** [holtzy/R-graph-gallery#95]
HI @holtzy 

First, let me thank you for the site, I think is one of the core documents anyone can find on the web for getting started with R and visualizations.

Following #91 , please note that the examples for maps are outdated. Many of the packages in use (e.g. **rgdal**, **rgeos** and **maptools**) are going to be retired (see https://r-spatial.org//r/2022/04/12/evolution.html) and **potentially not available any more on CRAN** (see https://geocompx.org/post/2023/rgdal-retirement/). Instead, **sf** is now the standard for reading map data and plot it (even **ggplot** handles these objects natively with `geom_sf()`)

While I think this is the most important issue on the map section (as [people is still using your tutorial actively](https://gis.stackexchange.com/questions/460615/using-a-downloaded-shapefile-in-ggplot2-and-r-readogr-error/460796) )there are some additional suggestions on this:

- The package **cartography** is in maintenance support (see http://riatelab.github.io/cartography/docs/) and a replacement package was created by the same developer (see **mapsf** https://riatelab.github.io/mapsf/).
- On this, maybe you may consider add also examples with **tmap**, that is a well-known package for cartography in R
- Regarding the section https://r-graph-gallery.com/278-the-maps-library.html, note that the [CRAN Task View: Spatial](https://cran.r-project.org/web/views/Spatial.html) provides an overview of additional packages that can be used to retrieve spatial data of the world (**rnaturalearth**, **giscoR**) and specific countries (**mapSpain**, **tigris**, **RCzechia**, **chilemapas**)
- Regarding background tiles , now **maptiles**  + **tidyterra** packages can be used as well as **ggmap** (see this [Q&A in stackoverflow](https://stackoverflow.com/questions/74733975/setting-crs-for-plotting-with-stamenmaps/74751521#74751521)) for accessing and plotting background tiles.

Regarding the retirement of **rgdal**, **rgeos** and maptools, I took the liberty of forking the repo and worked on it (see 327 choropleth page updated here https://dieghernan.github.io/R-graph-gallery/327-chloropleth-map-from-geojson-with-ggplot2.html). I can send a PR with the corresponding udpates if you find it interesting. 

In the meantime, the updates can be checked here: https://dieghernan.github.io/R-graph-gallery/map

Thanks

**Comment by dieghernan** [comment]
See a preview of the PR https://github.com/holtzy/R-graph-gallery/compare/master...dieghernan:R-graph-gallery:master?expand=1

**Comment by kadyb** [comment]
@holtzy, `{rgdal}` and `{rgeos}` have been archived on CRAN, so it would be worth updating these materials.

**Comment by holtzy** [comment]
Thanks for the clear explanations here! And thank you even more for your PR @dieghernan.

I am full this week. But prioritising this now. So it will be merged next Monday most likely.

🙏🙏🙏

**Comment by holtzy** [comment]
PR merged today. Thank you so much such an improvement
