### ISSUE TITLE
Add text over boxplot in base R

### ISSUE THREAD

**Issue by mcuilleret** [holtzy/R-graph-gallery#98]
Hi, there is an issue with this code, if we don't put a factor in this line, it doesn't work 

nbGroup <- nlevels(data$names)

It works when we do:
nbGroup <- nlevels(factor(data$names))

Thanks

**Comment by JosephBARBIERDARNAL** [comment]
Hi @mcuilleret , thanks a lot for your comment! This has now been fixed here #164 

@holtzy can close now
