### ISSUE TITLE
Scatterplot demo bug

### ISSUE THREAD

**Issue by genostack** [holtzy/R-graph-gallery#99]
In the page https://r-graph-gallery.com/274-map-a-variable-to-ggplot2-scatterplot.html
The demo code
`#Transparency
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, alpha=Species)) + 
    geom_point(size=6, color="#69b3a2") +
    theme_ipsum()

#Shape
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, shape=Species)) + 
    geom_point(size=6) +
    theme_ipsum()

#Size
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, shape=Species)) + 
    geom_point(size=6) +
    theme_ipsum()`

may be:
`#Transparency
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, alpha=Species)) + 
    geom_point(size=6, color="#69b3a2") +
    theme_ipsum()

#Shape
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, **_shape_**=Species)) + 
    geom_point(size=6, **color**="#69b3a2") +
    theme_ipsum()

#Size
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, **_size_**=Species)) + 
    geom_point(**color**="#69b3a2") +
    theme_ipsum()`

**Comment by JosephBARBIERDARNAL** [comment]
Hi @genostack ! thanks for your feedback! 

this will be fixed soon with #167
